on:
  # event to trigger action, e.g.
  push:
    # Sequence of patterns matched against refs/tags
    # tags:
      # - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      #  uses: actions/checkout@master
      # - name: Create Release
        # id: create_release
        # uses: ./
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
          # tag_name: ${{ github.ref }}
          # release_name: Release ${{ github.ref }}
          # draft: false
          # prerelease: false
